name: Auto Assign Issues
on:
  issues:
    types: [opened]

permissions:
  issues: write # Grant write permission to issues

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: "Auto-assign issue"
        uses: pozil/auto-assign-issue@v2
        with:
          assignees: shalper2,joseacunacarrera,edro15
          # teams: admins
          numOfAssignee: 1
          allowSelfAssign: false
          # Auto-assigns new issues to two users randomly chosen from listed ones
          # It won't self-assign to the issue author
          # TODO evaluate and eventually assign to team!
          # https://github.com/pozil/auto-assign-issue