name: Renovate

on:
  schedule:
    - cron: "0 0 1 * *"   # At 00:00 on day-of-month 1
  # Allow manual execution
  workflow_dispatch:

concurrency: renovate
permissions:
  contents: read

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          owner: "splunk-platform-apps"
          # The owner of the GitHub App installation
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.11
        env:
          LOG_LEVEL: debug
          # Onboarding not needed for self-hosted usage
          RENOVATE_ONBOARDING: "false"
        with:
          configurationFile: .github/renovate-config.js
          token: '${{ steps.get_token.outputs.token }}'
